### ISSUE TITLE
Unplayable with the OpenGL renderer and Nouveau

### ISSUE THREAD

**Issue by dokutan** [taisei-project/taisei#274] opened 2021-01-13 10:42 UTC
When using the OpenGL renderer on Linux with Nouveau there are graphical glitches, the OpenGL ES 3.0 renderer works without problems.
Attached are two screenshots and the log files with and without ``TAISEI_GL_DEBUG=1``.

![taisei_20210113_11-24-39-557](https://user-images.githubusercontent.com/54861821/104441004-62bc6780-5593-11eb-9fdc-45eae4bb9cf3.png)
![taisei_20210113_11-25-19-700](https://user-images.githubusercontent.com/54861821/104441007-63ed9480-5593-11eb-8af8-d8cd102341e7.png)

[log.txt](https://github.com/taisei-project/taisei/files/5808036/log.txt)
[log_TAISEI_GL_DEBUG=1.txt](https://github.com/taisei-project/taisei/files/5808039/log_TAISEI_GL_DEBUG.1.txt)

**Comment by Akaricchi** [comment] 2021-01-14 01:43
Thanks for the report. Bug confirmed on a GTX 680 (had to resurrect my old PC for this one). Not yet sure if this is our bug or Mesa's, will investigate soon.

**Comment by Akaricchi** [comment] 2021-01-15 17:51
Ok, so I've identified the problem - nouveau doesn't support `RGB16` texture attachments for framebuffers. Easy to fix by making it use RGBA16 instead (as it does for the GLES renderer).

However, I'm still not sure whether this is an oversight on my end, or a Mesa bug. I've filed a [Mesa bug report](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4101) to hopefully gain a better understanding of the spec, and possibly get it fixed on their end if applicable.

**Comment by dokutan** [comment] 2021-01-15 18:21
If this is indeed a bug in Mesa, it wouldn't make sense to fix it here, however if not, how difficult (and messy) would it be to detect Nouveau and switch to RGBA16 and the GL33 renderer, the GLES renderer or show an error message? I have had a look at the code but unfortunately my knowledge about OpenGL is extremely limited.

**Comment by Akaricchi** [comment] 2021-01-15 18:37
It would be fairly trivial. There is already a basic "workarounds" system in place to detect bad drivers; see https://github.com/taisei-project/taisei/blob/2f0f7543e8364cb31b3d07d75ac3fd24bbeec99d/src/renderer/glcommon/opengl.c#L703

**However**, if this isn't a Mesa bug, then the right thing wouldn't be to special-case nouveau, but to simply not assume that RGB16 is color-renderable. That's what the GLES path already does, since the GLES spec is a lot more clear on this (and GLES implementations tend to be stricter than vanilla OpenGL ones). All it takes is removing this one line, basically https://github.com/taisei-project/taisei/blob/2f0f7543e8364cb31b3d07d75ac3fd24bbeec99d/src/renderer/glcommon/texture.c#L136

**Comment by imirkin** [comment] 2021-01-15 23:57
You can use `GL_ARB_internalformat_query2` to find this out, e.g.

```
int internalFormat;
GetInternalformativ(GL_RENDERBUFFER, GL_RGB16, GL_INTERNALFORMAT_PREFERRED, 1, &buf);
```

should do the trick, I believe.

**Comment by Akaricchi** [comment] 2021-01-16 00:21
> You can use `GL_ARB_internalformat_query2` to find this out, e.g.

Yeah https://github.com/taisei-project/taisei/blob/2f0f7543e8364cb31b3d07d75ac3fd24bbeec99d/src/renderer/glcommon/texture.c#L101

But last time I checked, I think most of Mesa's implementation of that extension was a stub, and e.g. that query would still return `GL_RGB16` even if the driver used RGBA16 internally. I could be wrong though.

**Comment by imirkin** [comment] 2021-01-16 00:44
I admit I haven't tested that particular thing, but based on my read:

https://cgit.freedesktop.org/mesa/mesa/tree/src/mesa/main/formatquery.c#n929

which will call

https://cgit.freedesktop.org/mesa/mesa/tree/src/mesa/state_tracker/st_format.c#n1438

which in turn will do the "usual" format picking logic for those bindings, in this case for render target (dubious choice IMO for e.g. GL_TEXTURE_2D pname, but wtvr).

**Comment by Akaricchi** [comment] 2021-01-16 01:19
Alright, thanks. I'll give it a try.

**Closed** 2021-01-17 03:32 UTC
Labels: linux, rendering

**Comment by Akaricchi** [comment] 2021-01-17 03:36
Apparently the spec doesn't guarantee any RGB formats to be color-renderable, so I made taisei assume that they aren't for now. Please let me know if the fix works for you.

I'm also hooking up ARB_internalformat_query2 support for more robust feature detection on drivers that implement that extension.

**Comment by dokutan** [comment] 2021-01-17 14:12
I can confirm that the fix works perfectly for me. Thanks for your efforts.
