### ISSUE TITLE
Browser version issue

### ISSUE THREAD

**Issue by CableTV1123** [taisei-project/taisei#287] opened 2021-04-27 14:41 UTC
I'm on a chromebook and I tried playing the browser version and I just got a black screen in the play area when I started the game
I've tried messing withe the settings and nothing worked
the thing is the game still runs I can see the stuff like score updating but I can't see the game

**Comment by Akaricchi** [comment] 2021-04-27 15:30
Hi. This is a known issue, it has surfaced due to a WebGL change in recent-ish Chromium-based browsers. We're currently working on a minor update that will fix this problem. It should go online within this week.

**Comment by Akaricchi** [comment] 2021-05-02 08:36
This should be fixed [now that v1.3.2 is out](https://taisei-project.org/news/0013_v1.3.2). You might need to refresh the page with Ctrl+F5 or equivalent to clear the cache. Feel free to reopen the issue if you're still having problems.

**Comment by CableTV1123** [comment] 2021-05-03 11:32
It's still not working
I'm trying to play on an hp chromebook 11a g6 ee 
The thing is WebGL works on other sites

**Comment by Akaricchi** [comment] 2021-05-03 12:09
In the bottom right corner of the main menu, there is a version number displayed. Does it say `1.3.2` or `1.3.1`?

**Comment by CableTV1123** [comment] 2021-05-03 12:24
1.3.2

**Comment by CableTV1123** [comment] 2021-05-03 12:26
![image](https://user-images.githubusercontent.com/80400552/116875577-26b41d80-abe9-11eb-9983-f4f8495612ec.png)
I took a screenshot of somewhere in the log does anything look like it's not supposed to be there

**Comment by Akaricchi** [comment] 2021-05-03 12:46
That part looks fine. It would be more useful to see the javascript console during the black screen bug. I'm not familiar with Chrome OS, but assuming it works similarly to the regular Chrome browser on desktop, you can open the console by right-clicking somewhere on the page -> `Inspect` -> navigate to the `Console` tab. Then try starting a new game.

Also, go to [chrome://version](chrome://version) and take a screenshot of that.

**Comment by CableTV1123** [comment] 2021-05-03 12:57
I would the thing is I can't...

I'm using a school issued chromebook (why else would I be using a chromebook) and the tech people blocked the inspect 
I may be able to find an emulator for chrome os or something idk

**Comment by Akaricchi** [comment] 2021-05-03 12:59
Ok. Does `chrome://version` work at least? If we know which Chromium version the OS is based on, we can probably reproduce the problem in a regular desktop version of it.

**Comment by CableTV1123** [comment] 2021-05-03 13:01
![image](https://user-images.githubusercontent.com/80400552/116879018-1ce0e900-abee-11eb-8a41-cf792cd07eb2.png)
that good?

**Comment by Akaricchi** [comment] 2021-05-03 13:10
Hm, this is actually newer than what i've been testing on (89.0.4389.128). I'll try to get my hands on that build soon.

Meanwhile, can you also screenshot https://webglreport.com/?v=2 please?

**Comment by CableTV1123** [comment] 2021-05-03 13:12
![image](https://user-images.githubusercontent.com/80400552/116880124-9cbb8300-abef-11eb-8d46-40e7f6ddcb4b.png)

![image](https://user-images.githubusercontent.com/80400552/116880148-a7761800-abef-11eb-86a9-2500209dc88e.png)

**Comment by Akaricchi** [comment] 2021-05-04 13:40
Can't reproduce this on Chromium 90.0.4430.93. Without the JS console log there isn't much I can do about this, sorry.

**Comment by CableTV1123** [comment] 2021-05-04 14:32
ok

**Comment by StarWitch** [comment] 2021-05-06 19:46
I managed to reproduce this myself on macOS using Chrome, and I sent @Akaricchi a Spector.JS dump of the relevant frames.

**Comment by Akaricchi** [comment] 2021-05-06 23:45
Should be fixed now.

**Closed by Akaricchi** 2021-05-06 23:45 UTC
Labels: emscripten, help wanted, rendering

**Comment by CableTV1123** [comment] 2021-05-07 11:31
Just played it 
it works thanks! :D

**Comment by CableTV1123** [comment] 2021-05-07 12:05
I don't know if this would be something you're able to fix or if it's just my chromebook but it's been doing what I like to call "keyboard drift" 
sometimes it'll just stop reading my inputs for a few seconds and it's kinda annoying
