### ISSUE TITLE
"Menu Scrolling Not Working on Steam Deck"

### ISSUE THREAD

**Issue by saim473706** [taisei-project/taisei#394] opened 2024-12-19 18:02 UTC
"After updating to version 1.4.2 on the Steam Deck (Linux, Flathub installation), the game menu scrolls multiple options (2 or more) when pressing the D-pad. It seems like the directional inputs aren't being buffered correctly in the menu. 

Apologies for the limited details; this is the most accurate description I can provide based on my knowledge."

**Comment by Akaricchi** [comment] 2024-12-19 23:08
Bizarre duplicate of #388

**Closed by Akaricchi** 2024-12-19 23:08 UTC
